### PR TITLE
snowflake-ml-python 1.5.4

### PR DESCRIPTION
**Pull request by lorepirri**
snowflake-ml-python 1.5.4

**Destination channel:** defaults

### Links

- [PKG-5298]
- dev_url (pypi): https://github.com/snowflakedb/snowflake-ml-python/tree/1.5.4
- [1.5.3...1.5.4](https://github.com/snowflakedb/snowflake-ml-python/compare/1.5.3...1.5.4) diff: https://github.com/snowflakedb/snowflake-ml-python/compare/1.5.3...1.5.4
- pypi: https://pypi.org/project/snowflake-ml-python/1.5.4
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.5.4

### Explanation of changes:

- bump version
- add `openjpeg !=2.4.0=*_1` for `win` see [diff 1.5.3...1.5.4](https://github.com/snowflakedb/snowflake-ml-python/compare/1.5.3...1.5.4), see ticket.
- removed comments in the `run_constrained`. They are not needed. In this way, the next update will be easier to review. See `ci/conda_recipe/meta.yaml` in the [diff 1.5.3...1.5.4](https://github.com/snowflakedb/snowflake-ml-python/compare/1.5.3...1.5.4).

### Notes for the reviewers

- To review `run` and `run_constrained` see `ci/conda_recipe/meta.yaml` in the [diff 1.5.3...1.5.4](https://github.com/snowflakedb/snowflake-ml-python/compare/1.5.3...1.5.4).

[PKG-5298]: https://anaconda.atlassian.net/browse/PKG-5298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by cbouss — APPROVED** [review]

**Review by danpetry — APPROVED** [review]
Note that the ci/conda_recipe/meta.yaml isn't the source of truth, the requirements.yml is:
https://anaconda.slack.com/archives/C02K52E033M/p1715683894631949?thread_ts=1715675443.568009&cid=C02K52E033M
It might be worth adding that to the comments near the top of the recipe

**Comment by danpetry** [comment]
And ideally, trying to get snowflake to make sure we can rely on that meta.yaml

**Comment by lorepirri** [comment]
> Note that the ci/conda_recipe/meta.yaml isn't the source of truth, the requirements.yml is: https://anaconda.slack.com/archives/C02K52E033M/p1715683894631949?thread_ts=1715675443.568009&cid=C02K52E033M It might be worth adding that to the comments near the top of the recipe

`requirements.yml` didn't catch the `openjpeg !=2.4.0=*_1` fix for `win`

> And ideally, trying to get snowflake to make sure we can rely on that meta.yaml

done, waiting for an answer

**Comment by danpetry** [comment]
ah ok so do you need to add that we should look in the meta.yaml as well...? was the openjpeg addition really required...?

**Comment by lorepirri** [comment]
> ah ok so do you need to add that we should look in the meta.yaml as well...? 

waiting for an official answer from SF

> was the openjpeg addition really required...?

yes, see ticket [PKG-5298]

**Pull request merged**
