### PR TITLE
upgrade to 1.2.0

### PR DESCRIPTION
**Pull request by M-Waszkiewicz-Anaconda**
snowflake-ml-python 1.2.0 :snowflake:

**Destination channel:**  defaults

### Links

- [{ticket_number}](https://anaconda.atlassian.net/browse/PKG-3789) 
- [Upstream repository](https://github.com/snowflakedb/snowflake-ml-python/tree/1.2.0)
- [Upstream changelog/diff](https://github.com/snowflakedb/snowflake-ml-python/compare/1.1.2...1.2.0)

### CODE REVIEW

**Comment by M-Waszkiewicz-Anaconda** [comment]
windows build successful:

```
(base) %SRC_DIR%>conda activate "%PREFIX%"
import: 'snowflake.ml'
import: 'snowflake.ml.fileset'
import: 'snowflake.ml.model'
import: 'snowflake.ml.modeling'
import: 'snowflake.ml.registry'
import: 'snowflake.ml.utils'
import: 'snowflake.ml'
import: 'snowflake.ml.fileset'
import: 'snowflake.ml.model'
import: 'snowflake.ml.modeling'
import: 'snowflake.ml.registry'
import: 'snowflake.ml.utils'

Resource usage statistics from testing snowflake-ml-python:
   Process count: 2
   CPU time: Sys=0:00:00.1, User=0:00:00.2
   Memory: 74.3M
   Disk usage: 1.5K
   Time elapsed: 0:00:04.1


TEST END: C:\Users\48667\miniconda3\conda-bld\win-64\snowflake-ml-python-1.2.0-py311h2bbff1b_0.tar.bz2
Renaming work directory 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1705965511509\work' to 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1705965511509\work_moved_snowflake-ml-python-1.2.0-py311h2bbff1b_0_win-64_main_build_loop'
INFO:conda_build.utils:Renaming work directory 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1705965511509\work' to 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1705965511509\work_moved_snowflake-ml-python-1.2.0-py311h2bbff1b_0_win-64_main_build_loop'
shutil.move(work)=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1705965511509\work, dest=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1705965511509\work_moved_snowflake-ml-python-1.2.0-py311h2bbff1b_0_win-64_main_build_loop)
INFO:conda_build.utils:shutil.move(work)=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1705965511509\work, dest=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1705965511509\work_moved_snowflake-ml-python-1.2.0-py311h2bbff1b_0_win-64_main_build_loop)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(188): Could not remove or rename C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1705965511509\_build_env\Library\lib\modules.  Please remove this file manually (you may need to reboot to free file handles)
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:


# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
anaconda upload ^
    C:\Users\48667\miniconda3\conda-bld\win-64\snowflake-ml-python-1.2.0-py311h2bbff1b_0.tar.bz2
anaconda_upload is not set.  Not uploading wheels: []

INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "snowflake-ml-python-1.2.0-py311h2bbff1b_0": {
    "recipe": {
      "c_compiler": "vs2017",
      "channel_targets": "defaults",
      "target_platform": "win-64"
    }
  }
}


####################################################################################
Resource usage summary:

Total time: 0:10:11.0
CPU usage: sys=0:00:34.8, user=0:01:45.6
Maximum memory usage observed: 996.0M
Total disk usage observed (not including envs): 15.4G
```

**Review by danpetry — APPROVED** [review]
Just curious why Windows needs a manual build? Could be useful to put the reason in the feedstock so some future engineer knows when to remove the skip

**Comment by M-Waszkiewicz-Anaconda** [comment]
> Just curious why Windows needs a manual build? Could be useful to put the reason in the feedstock so some future engineer knows when to remove the skip

because of missing symlinks in windows CI builders

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Comment by danpetry** [comment]
We had a windows symlink issue on pytorch, and manually copied the files during the build. see https://github.com/AnacondaRecipes/pytorch-feedstock/blob/ac911a90b8d2d068ca6e8f432b26427808c7189b/recipe/bld_pytorch.bat#L5

**Pull request merged**
