### PR TITLE
snowflake-ml-python 1.7.2 

### PR DESCRIPTION
**Pull request by Cansisti**
snowflake-ml-python 1.7.2 

**Destination channel:** Defaults

### Links

- [PKG-6270]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.7.2
- conda_forge:    https://github.com/conda-forge/snowflake-ml-python-feedstock/blob/main/recipe/meta.yaml
- pypi:           https://pypi.org/project/snowflake-ml-python/1.7.2
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.7.2

### Explanation of changes:

- new version number

[PKG-6270]: https://anaconda.atlassian.net/browse/PKG-6270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ifitchet** [comment]
The skip should be `... or >=py311`, shouldn't it? https://inspector.pypi.io/project/snowflake-ml-python/1.7.2/packages/86/5b/1240490544106f8d70914d4140e151664e43b6b4d64ae50d2f16f5d7f6e8/snowflake_ml_python-1.7.2.tar.gz/snowflake_ml_python-1.7.2/pyproject.toml#line.8

**Comment by Cansisti** [comment]
> The skip should be `... or >=py311`, shouldn't it? https://inspector.pypi.io/project/snowflake-ml-python/1.7.2/packages/86/5b/1240490544106f8d70914d4140e151664e43b6b4d64ae50d2f16f5d7f6e8/snowflake_ml_python-1.7.2.tar.gz/snowflake_ml_python-1.7.2/pyproject.toml#line.8

@ifitchet 
`py311` is supported according to the above, and `>=py311` would skip it, so I should not, I believe.

**Comment by ifitchet** [comment]
> @ifitchet `py311` is supported according to the above, and `>=py311` would skip it, so it should not, I believe.

Maybe I can't do negated logic... 🤷 😆

**Review by ifitchet — APPROVED** [review]

**Review by lorepirri — APPROVED** [review]
Thanks!

**Pull request merged**
