### PR TITLE
[PKG-2810] snowflake-ml-python 1.0.8

### PR DESCRIPTION
**Pull request by M-Waszkiewicz-Anaconda**
Changelog: https://github.com/snowflakedb/snowflake-ml-python/blob/1.0.8/CHANGELOG.md
License: https://github.com/snowflakedb/snowflake-ml-python/blob/1.0.8/LICENSE.txt
Requirements:
- https://github.com/snowflakedb/snowflake-ml-python/blob/1.0.8/snowflake/ml/requirements.bzl
- https://github.com/snowflakedb/snowflake-ml-python/blob/1.0.8/third_party/rules_conda/conda.bzl

Actions:
1. Add a comment about `bazel` **rules** with underlying `Miniconda` and `conda-libmamba-solver` hardcoded versions that can affect the build process in the future.
2. Update dependencies in `run` and `run_constrained`

### CODE REVIEW

**Review by M-Waszkiewicz-Anaconda — COMMENTED** [review]
windows build on local machine output:
(%PREFIX%) %SRC_DIR%>"%PREFIX%\python.exe" -s "%SRC_DIR%\run_test.py"
import: 'snowflake.ml'
import: 'snowflake.ml.fileset'
import: 'snowflake.ml.model'
import: 'snowflake.ml.modeling'
import: 'snowflake.ml.registry'
import: 'snowflake.ml.training_dataset'
import: 'snowflake.ml.utils'
import: 'snowflake.ml'
import: 'snowflake.ml.fileset'
import: 'snowflake.ml.model'
import: 'snowflake.ml.modeling'
import: 'snowflake.ml.registry'
import: 'snowflake.ml.training_dataset'
import: 'snowflake.ml.utils'

(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit /B 1

Resource usage statistics from testing snowflake-ml-python:
   Process count: 1
   CPU time: Sys=-, User=-
   Memory: 4.3M
   Disk usage: 1.7K
   Time elapsed: 0:00:02.1


TEST END: C:\Users\48667\miniconda3\conda-bld\win-64\snowflake-ml-python-1.0.8-py38h2bbff1b_0.tar.bz2
Renaming work directory 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1694792388603\work' to 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1694792388603\work_moved_snowflake-ml-python-1.0.8-py38h2bbff1b_0_win-64_main_build_loop'
INFO:conda_build.utils:Renaming work directory 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1694792388603\work' to 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1694792388603\work_moved_snowflake-ml-python-1.0.8-py38h2bbff1b_0_win-64_main_build_loop'
shutil.move(work)=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1694792388603\work, dest=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1694792388603\work_moved_snowflake-ml-python-1.0.8-py38h2bbff1b_0_win-64_main_build_loop)
INFO:conda_build.utils:shutil.move(work)=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1694792388603\work, dest=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1694792388603\work_moved_snowflake-ml-python-1.0.8-py38h2bbff1b_0_win-64_main_build_loop)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(188): Could not remove or rename C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1694792388603\_build_env\Library\lib\modules.  Please remove this file manually (you may need to reboot to free file handles)
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:


# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
anaconda upload ^
    C:\Users\48667\miniconda3\conda-bld\win-64\snowflake-ml-python-1.0.8-py38h2bbff1b_0.tar.bz2
anaconda_upload is not set.  Not uploading wheels: []

INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "snowflake-ml-python-1.0.8-py38h2bbff1b_0": {
    "recipe": {
      "c_compiler": "vs2017",
      "channel_targets": "defaults",
      "target_platform": "win-64"
    }
  }
}


####################################################################################
Resource usage summary:

Total time: 0:11:07.9
CPU usage: sys=0:00:54.2, user=0:02:09.6
Maximum memory usage observed: 919.3M
Total disk usage observed (not including envs): 13.1G


####################################################################################
Source and build intermediates have been left in C:\Users\48667\miniconda3\conda-bld.
There are currently 8 accumulated.
To remove them, you can run the ```conda build purge``` command

**Comment by M-Waszkiewicz-Anaconda** [comment]
now, lets wait with it for @Arishamays1 to finish snowpark we we would build also for py311

**Comment by M-Waszkiewicz-Anaconda** [comment]
we would upload to default py < 3.11 and to snowflake the py 3.11 version as its dependency snowflake-snowpark 1.8.0 goes to snowflake, too

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Review by SC426 — APPROVED** [review]

**Pull request merged**
