### PR TITLE
[PKG-5611] snowflake-ml-python 1.6.0

### PR DESCRIPTION
**Pull request by psteyer**
snowflake-ml-python 1.6.0

**Destination channel:** defaults

### Links

- [PKG-5611](https://anaconda.atlassian.net/browse/PKG-5611) 
- [Upstream repository](https://github.com/snowflakedb/snowflake-ml-python/tree/1.6.0)
- [Upstream changelog/diff](https://github.com/snowflakedb/snowflake-ml-python/compare/1.6.0...1.6.1)

### Explanation of changes:

- build 1.6.0
- changed build number to 100

[PKG-5611]: https://anaconda.atlassian.net/browse/PKG-5611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by lorepirri — APPROVED** [review]
LGTM,
the diff with the 1.6.1 shows not changes in deps: https://github.com/snowflakedb/snowflake-ml-python/compare/1.6.0...1.6.1

Thanks for creating this versioned feedstock

**Comment by Jrice1317** [comment]
The `osx-arm64` build is failing. Is that expected?

**Comment by lorepirri** [comment]
> The `osx-arm64` build is failing. Is that expected?

```
08/30/24 18:50:51  INFO   FATAL: corrupt installation: file '/var/tmp/_bazel_builder/install/c9953e604a7fd2c8687958db3d861111/A-server.jar' is missing or modified.  Please remove                           
                          '/var/tmp/_bazel_builder/install/c9953e604a7fd2c8687958db3d861111' and try again.                                                                                                  
```

**Comment by psteyer** [comment]
> The `osx-arm64` build is failing. Is that expected?

Should be good to go!

**Review by Arishamays1 — APPROVED** [review]

**Pull request merged**
